// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package urlutilities.proxies;

public class URLParse
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject uRLParseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "URLUtilities.URLParse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Protocol("Protocol"),
		Host("Host"),
		Port("Port"),
		Hostname("Hostname"),
		Path("Path"),
		Query("Query"),
		Hash("Hash"),
		Username("Username"),
		Password("Password"),
		Origin("Origin");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public URLParse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected URLParse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject uRLParseMendixObject)
	{
		if (uRLParseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, uRLParseMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.uRLParseMendixObject = uRLParseMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'URLParse.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static urlutilities.proxies.URLParse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return urlutilities.proxies.URLParse.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static urlutilities.proxies.URLParse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new urlutilities.proxies.URLParse(context, mendixObject);
	}

	public static urlutilities.proxies.URLParse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return urlutilities.proxies.URLParse.initialize(context, mendixObject);
	}

	public static java.util.List<urlutilities.proxies.URLParse> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> urlutilities.proxies.URLParse.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Protocol
	 */
	public final java.lang.String getProtocol()
	{
		return getProtocol(getContext());
	}

	/**
	 * @param context
	 * @return value of Protocol
	 */
	public final java.lang.String getProtocol(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Protocol.toString());
	}

	/**
	 * Set value of Protocol
	 * @param protocol
	 */
	public final void setProtocol(java.lang.String protocol)
	{
		setProtocol(getContext(), protocol);
	}

	/**
	 * Set value of Protocol
	 * @param context
	 * @param protocol
	 */
	public final void setProtocol(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String protocol)
	{
		getMendixObject().setValue(context, MemberNames.Protocol.toString(), protocol);
	}

	/**
	 * @return value of Host
	 */
	public final java.lang.String getHost()
	{
		return getHost(getContext());
	}

	/**
	 * @param context
	 * @return value of Host
	 */
	public final java.lang.String getHost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Host.toString());
	}

	/**
	 * Set value of Host
	 * @param host
	 */
	public final void setHost(java.lang.String host)
	{
		setHost(getContext(), host);
	}

	/**
	 * Set value of Host
	 * @param context
	 * @param host
	 */
	public final void setHost(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String host)
	{
		getMendixObject().setValue(context, MemberNames.Host.toString(), host);
	}

	/**
	 * @return value of Port
	 */
	public final java.lang.String getPort()
	{
		return getPort(getContext());
	}

	/**
	 * @param context
	 * @return value of Port
	 */
	public final java.lang.String getPort(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Port.toString());
	}

	/**
	 * Set value of Port
	 * @param port
	 */
	public final void setPort(java.lang.String port)
	{
		setPort(getContext(), port);
	}

	/**
	 * Set value of Port
	 * @param context
	 * @param port
	 */
	public final void setPort(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String port)
	{
		getMendixObject().setValue(context, MemberNames.Port.toString(), port);
	}

	/**
	 * @return value of Hostname
	 */
	public final java.lang.String getHostname()
	{
		return getHostname(getContext());
	}

	/**
	 * @param context
	 * @return value of Hostname
	 */
	public final java.lang.String getHostname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Hostname.toString());
	}

	/**
	 * Set value of Hostname
	 * @param hostname
	 */
	public final void setHostname(java.lang.String hostname)
	{
		setHostname(getContext(), hostname);
	}

	/**
	 * Set value of Hostname
	 * @param context
	 * @param hostname
	 */
	public final void setHostname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String hostname)
	{
		getMendixObject().setValue(context, MemberNames.Hostname.toString(), hostname);
	}

	/**
	 * @return value of Path
	 */
	public final java.lang.String getPath()
	{
		return getPath(getContext());
	}

	/**
	 * @param context
	 * @return value of Path
	 */
	public final java.lang.String getPath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Path.toString());
	}

	/**
	 * Set value of Path
	 * @param path
	 */
	public final void setPath(java.lang.String path)
	{
		setPath(getContext(), path);
	}

	/**
	 * Set value of Path
	 * @param context
	 * @param path
	 */
	public final void setPath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String path)
	{
		getMendixObject().setValue(context, MemberNames.Path.toString(), path);
	}

	/**
	 * @return value of Query
	 */
	public final java.lang.String getQuery()
	{
		return getQuery(getContext());
	}

	/**
	 * @param context
	 * @return value of Query
	 */
	public final java.lang.String getQuery(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Query.toString());
	}

	/**
	 * Set value of Query
	 * @param query
	 */
	public final void setQuery(java.lang.String query)
	{
		setQuery(getContext(), query);
	}

	/**
	 * Set value of Query
	 * @param context
	 * @param query
	 */
	public final void setQuery(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String query)
	{
		getMendixObject().setValue(context, MemberNames.Query.toString(), query);
	}

	/**
	 * @return value of Hash
	 */
	public final java.lang.String getHash()
	{
		return getHash(getContext());
	}

	/**
	 * @param context
	 * @return value of Hash
	 */
	public final java.lang.String getHash(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Hash.toString());
	}

	/**
	 * Set value of Hash
	 * @param hash
	 */
	public final void setHash(java.lang.String hash)
	{
		setHash(getContext(), hash);
	}

	/**
	 * Set value of Hash
	 * @param context
	 * @param hash
	 */
	public final void setHash(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String hash)
	{
		getMendixObject().setValue(context, MemberNames.Hash.toString(), hash);
	}

	/**
	 * @return value of Username
	 */
	public final java.lang.String getUsername()
	{
		return getUsername(getContext());
	}

	/**
	 * @param context
	 * @return value of Username
	 */
	public final java.lang.String getUsername(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Username.toString());
	}

	/**
	 * Set value of Username
	 * @param username
	 */
	public final void setUsername(java.lang.String username)
	{
		setUsername(getContext(), username);
	}

	/**
	 * Set value of Username
	 * @param context
	 * @param username
	 */
	public final void setUsername(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.Username.toString(), username);
	}

	/**
	 * @return value of Password
	 */
	public final java.lang.String getPassword()
	{
		return getPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of Password
	 */
	public final java.lang.String getPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Password.toString());
	}

	/**
	 * Set value of Password
	 * @param password
	 */
	public final void setPassword(java.lang.String password)
	{
		setPassword(getContext(), password);
	}

	/**
	 * Set value of Password
	 * @param context
	 * @param password
	 */
	public final void setPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String password)
	{
		getMendixObject().setValue(context, MemberNames.Password.toString(), password);
	}

	/**
	 * @return value of Origin
	 */
	public final java.lang.String getOrigin()
	{
		return getOrigin(getContext());
	}

	/**
	 * @param context
	 * @return value of Origin
	 */
	public final java.lang.String getOrigin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Origin.toString());
	}

	/**
	 * Set value of Origin
	 * @param origin
	 */
	public final void setOrigin(java.lang.String origin)
	{
		setOrigin(getContext(), origin);
	}

	/**
	 * Set value of Origin
	 * @param context
	 * @param origin
	 */
	public final void setOrigin(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String origin)
	{
		getMendixObject().setValue(context, MemberNames.Origin.toString(), origin);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return uRLParseMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final urlutilities.proxies.URLParse that = (urlutilities.proxies.URLParse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
